apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name }}
spec:
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce