---
- name: Deploy Minecraft server
  hosts: localhost
  become: yes
  vars_prompt:
    - name: container_name
      prompt: "Enter the name of the Minecraft server container"
      private: no
  tasks:
    - name: Create Docker Compose file
      template:
        src: minecraft_server_docker_compose.yml.j2
        dest: /tmp/minecraft_server_docker_compose.yml
      vars:
        container_name: "{{ container_name }}"

    - name: Deploy Minecraft server using Docker Compose
      shell: |
        cd /tmp
        docker-compose up -d
      args:
        chdir: /tmp