apiVersion: v1
kind: Deployment
metadata:
  name: minecarft-server
  namespace: minecraft
  labels:
    app: minecraft
    release: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecarft
      release: minecarft
  template:
    metadata:
      labels:
        app: minecraft
        release: minecraft
    spec:
      containers:
        - name: minecarft
          image: asabhi6776/minecraft:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: test
              value: test
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 25565
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /minecraft
              name: data
      nodeSelector:
        memory: high
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "mine-chest"