apiVersion: v1
kind: Service
metadata:
  name: minecarft
spec:
  selector:
    app: minecarft
    release: minecraft
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: TCP
  type: ClusterIP
  